In [87]:
import pandas as pd
import numpy as np

In [88]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [89]:
df.head(n=7)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
5,2007,USA,Hybrid,Front-wheel drive,2,2290,6,266.0,4260,18.8,31.2
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8


**Q1. Pandas version**
- answer: `3.0.6`


In [90]:
pd.__version__

'3.0.6'

**ًQ2. How many records are in the dataset?**
- answer: $10000$

In [91]:
df.shape[0]

10000

---

**Q3. How many fuel types are presented in the dataset?**
- answer: $3$

In [92]:
df['fuel_type'].nunique()

3

---

**Q4. How many columns in the dataset have missing values?**
- answer: $2$ 

In [93]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [94]:
(df.isnull().sum() != 0).sum()

np.int64(2)

---

**Q5. What's the maximum fuel efficiency of cars from Asia?**
- answer: $41.2$

```$
SELECT
    origin,
    MAX(fuel_efficiency_mpg)
FROM cars
GROUP BY origin
HAVING origin = 'Asia'
```

In [95]:
df.groupby('origin')['fuel_efficiency_mpg'].max()['Asia']

np.float64(41.2)

```$
SELECT MAX(fuel_efficiency_mpg)
FROM cars
WHERE origin = 'Asia'
```

In [96]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

---

**Q6. Median value of horsepower**
1. Find the median value of the `horsepower` column in the dataset.
2. Next, calculate the most frequent value of the same `horsepower` column.
3. Use the `fillna` method to fill the missing values in the `horsepower` column with the most frequent value from the previous step.
4. Now, calculate the median value of `horsepower` once again.

**Has it changed?**
- Yes, it increased
- Yes, it decreased $\checkmark$
- No

In [97]:
median = df['horsepower'].median()
median

np.float64(254.0)

In [98]:
most_frequent_value = df['horsepower'].value_counts().index[0]
most_frequent_value

np.float64(252.0)

In [99]:
new_median = df['horsepower'].fillna(most_frequent_value).median()
new_median

np.float64(252.0)

In [100]:
median - new_median

np.float64(2.0)

---

**Q7. Sum of weights**
1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

- answer: $0.369$


In [101]:
asia_cars = df[df['origin'] == 'Asia']

$X$

In [102]:
X = asia_cars[['vehicle_weight', 'model_year']].head(n=7).values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

$X^{T}.X$

In [103]:
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

$\left ( X^{T}X\right )^{-1}$

In [104]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

$y$

In [105]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

$\left ( X^{T}X\right )^{-1}.X^{T}.y$

In [106]:
w = XTX_inv.dot(X.T).dot(y)

In [107]:
w.sum()

np.float64(0.36919696904925486)

---

---