In [2]:
import numpy as np

In [3]:
u = np.array([2, 4, 5, 6])
2 * u

array([ 4,  8, 10, 12])

In [4]:
v = np.array([1, 0, 0, 2])
u + v

array([3, 4, 5, 8])

In [5]:
u * v

array([ 2,  0,  0, 12])

In [6]:
u.shape, v.shape

((4,), (4,))

In [7]:
u.shape[0]

4

In [8]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result += u[i] * v[i]
    return result

vector_vector_multiplication(u, v)

np.float64(14.0)

In [9]:
u.dot(v)

np.int64(14)

In [10]:
U = np.array([[2, 4, 5, 6],
              [1, 2, 1, 2],
              [3, 1, 2, 1]])
U.shape

(3, 4)

In [11]:
v = np.array([1, 0.5, 2, 1])

In [12]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    n = U.shape[0]
    result = np.zeros(U.shape[0])
    for i in range(n):
        result[i] = vector_vector_multiplication(U[i], v)
    return result

matrix_vector_multiplication(U, v)

array([20. ,  6. ,  8.5])

In [13]:
U.dot(v)

array([20. ,  6. ,  8.5])

In [14]:
U.shape

(3, 4)

In [15]:
V = np.array([[1, 1, 2],
              [0, 0.5, 1],
              [0, 2, 1],
              [2, 1, 0]])
V.shape

(4, 3)

In [17]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    n = V.shape[1]
    result = np.zeros((U.shape[0], V.shape[1]))
    for i in range(n):
        result[:, i] = matrix_vector_multiplication(U, V[:, i])
    return result

matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [18]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [20]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
V, I

(array([[1. , 1. , 2. ],
        [0. , 0.5, 1. ],
        [0. , 2. , 1. ],
        [2. , 1. , 0. ]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [28]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [30]:
V.shape

(4, 3)

In [31]:
Vs = V[[0, 1 ,2]]
Vs.shape

(3, 3)

In [32]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [34]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [35]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
B = np.array([
    [0, 1, 1],
    [1, 2, 3],
    [2, 3, 5]
])
np.linalg.inv(B)

LinAlgError: Singular matrix

In [37]:
A = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

In [38]:
b = np.array([1, 2, 3])

In [40]:
x = np.linalg.solve(A, b)
x

array([0., 1., 0.])

In [41]:
A.dot(x)

array([1., 2., 3.])