In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.ones((2, 2), dtype=bool)

array([[ True,  True],
       [ True,  True]])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
np.full((2, 2), 3.14)

array([[3.14, 3.14],
       [3.14, 3.14]])

In [8]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [9]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])
b.shape, b

((2, 3),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [10]:
a[2]

np.int64(3)

In [11]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(stop=10, step=2, dtype=int)

array([0, 2, 4, 6, 8])

In [15]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [17]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [18]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
n = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
n[0, 1]

np.int64(2)

In [21]:
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [22]:
n[2]

array([7, 8, 9])

In [23]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [24]:
n[..., 1]

array([20,  5,  1])

In [25]:
n[:, 1]

array([20,  5,  1])

In [26]:
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [27]:
np.random.rand(5, 2)

array([[2.43065628e-01, 7.75375382e-01],
       [4.55334100e-01, 2.64799941e-01],
       [1.76226223e-01, 7.42070258e-01],
       [8.36184857e-01, 2.26065415e-01],
       [7.01366200e-01, 6.43810485e-04]])

In [28]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [29]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [30]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [31]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [32]:
a + 1

array([1, 2, 3, 4, 5])

In [33]:
a * 2

array([0, 2, 4, 6, 8])

In [34]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [35]:
a

array([0, 1, 2, 3, 4])

In [36]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [37]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [38]:
a >= 2

array([False, False,  True,  True,  True])

In [39]:
a

array([0, 1, 2, 3, 4])

In [40]:
a[a >= 2]

array([2, 3, 4])

In [41]:
a

array([0, 1, 2, 3, 4])

In [42]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [43]:
a > b

array([False, False,  True,  True,  True])

In [44]:
a[a > b]

array([2, 3, 4])

In [45]:
a

array([0, 1, 2, 3, 4])

In [46]:
a.min()

np.int64(0)

In [47]:
a.max()

np.int64(4)

In [48]:
a.mean()

np.float64(2.0)

In [49]:
a.std()

np.float64(1.4142135623730951)

In [50]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [51]:
n.min()

np.int64(0)

In [52]:
np.repeat(0.5, 10)

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [53]:
np.repeat([0, 1], 5)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [54]:
arr = np.repeat([0, 1], [2, 3])

In [55]:
arr

array([0, 0, 1, 1, 1])

In [56]:
arr[[1, 2, 3]]

array([0, 1, 1])

In [57]:
zeros = np.zeros(10, dtype=np.uint8)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [58]:
np.random.seed(2)
noise = 0.01 * np.random.rand(5)
noise

array([0.00435995, 0.00025926, 0.00549662, 0.00435322, 0.00420368])

In [59]:
numbers = np.arange(5)
numbers

array([0, 1, 2, 3, 4])

In [60]:
result = numbers + noise
result.round(4)

array([0.0044, 1.0003, 2.0055, 3.0044, 4.0042])

In [61]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [62]:
np.exp(pred)

array([1.55270722, 1.03045453, 1.73325302])

In [63]:
np.log(pred)

array([-0.82098055, -3.5065579 , -0.597837  ])

In [65]:
np.random.seed(2)
pred1 = np.random.rand(3) >= 0.3
pred2 = np.random.rand(3) >= 0.4

In [66]:
pred1, pred2

(array([ True, False,  True]), array([ True,  True, False]))

In [67]:
pred1 & pred2

array([ True, False, False])

In [68]:
pred1 | pred2

array([ True,  True,  True])

In [69]:
pred1 ^ pred2

array([False,  True,  True])

In [70]:
np.random.seed(2)
matrix = np.random.rand(4, 3).round(2)
matrix

array([[0.44, 0.03, 0.55],
       [0.44, 0.42, 0.33],
       [0.2 , 0.62, 0.3 ],
       [0.27, 0.62, 0.53]])

In [71]:
matrix.max()

np.float64(0.62)

In [72]:
matrix.max(axis=0)

array([0.44, 0.62, 0.55])

In [73]:
matrix.max(axis=1)

array([0.55, 0.44, 0.62, 0.62])

In [74]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [75]:
np.sort(pred)

array([0.03, 0.44, 0.44, 0.55])

In [76]:
pred

array([0.44, 0.03, 0.55, 0.44])

In [77]:
pred.sort()
pred

array([0.03, 0.44, 0.44, 0.55])

In [78]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [79]:
idx = pred.argsort()
idx

array([1, 0, 3, 2])

In [80]:
pred[idx]

array([0.03, 0.44, 0.44, 0.55])

In [81]:
pred

array([0.44, 0.03, 0.55, 0.44])

In [82]:
rng = np.arange(12)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
rng.shape

(12,)

In [84]:
rng.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [85]:
rng.reshape(4, 3, order='F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [86]:
vec = np.arange(3)
vec

array([0, 1, 2])

In [87]:
mat = np.arange(6).reshape(3, 2)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [88]:
np.concatenate([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [89]:
np.hstack([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [93]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [90]:
np.hstack([mat, mat])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [91]:
np.concatenate([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [95]:
np.concatenate([mat, mat], axis=1)

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [97]:
vec, mat

(array([0, 1, 2]),
 array([[0, 1],
        [2, 3],
        [4, 5]]))

In [96]:
np.column_stack([vec, mat])

array([[0, 0, 1],
       [1, 2, 3],
       [2, 4, 5]])

In [98]:
np.column_stack([vec, vec])

array([[0, 0],
       [1, 1],
       [2, 2]])

In [99]:
vec

array([0, 1, 2])

In [102]:
np.hstack([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [103]:
np.vstack([vec, vec])

array([[0, 1, 2],
       [0, 1, 2]])

In [105]:
np.hstack([mat, mat])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [104]:
np.vstack([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [108]:
vec

array([0, 1, 2])

In [110]:
mat.T

array([[0, 2, 4],
       [1, 3, 5]])

In [112]:
np.vstack([vec, mat.T])

array([[0, 1, 2],
       [0, 2, 4],
       [1, 3, 5]])

In [114]:
mat = np.arange(15).reshape(5, 3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [117]:
mat[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [118]:
mat[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [119]:
mat[[1, 2]]

array([[3, 4, 5],
       [6, 7, 8]])

In [120]:
mat[:, :2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [121]:
mat[..., [0, 1]]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [122]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [123]:
mat[[3, 0, 1]]

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [124]:
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [125]:
mat[[1, 3]]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [127]:
mat[:, 0] % 2 == 1

array([False,  True, False,  True, False])

In [128]:
mat[mat[:, 0] % 2 == 1]

array([[ 3,  4,  5],
       [ 9, 10, 11]])